# dhcpd.conf
#
# Configuration file for ISC dhcpd (see 'man dhcpd.conf')
#

# Import key file for Dynamic DNS
include "/etc/dhcp/ddns.key";

option domain-name-servers 10.0.11.1;
option subnet-mask 255.255.255.0;
option routers 10.0.11.1;
authoritative;

subnet 10.0.11.0 netmask 255.255.255.0 {
  range 10.0.11.100 10.0.11.199;
  option domain-name "mo-net.lan";
  option domain-search "mo-net.lan";
  option ntp-server "ntp.mo-net.lan";
}

ddns-updates on;
ddns-update-style interim;
ddns-domainname "mo-net.lan.";
ddns-rev-domainname "in-addr.arpa.";
deny client-updates;
do-forward-updates on;
update-optimization on;
update-conflict-detection on;

zone mo-net.lan. {
  primary 10.0.11.1;
  key ddns-key;  # Ensure this matches the key file
}

zone 10.0.11.in-addr.arpa. {
  primary 10.0.11.1;
  key ddns-key;
}

# Lease time configuration
default-lease-time 86400;  # 1 day
max-lease-time 604800;  # 1 week

# Logging for troubleshooting
log-facility local7;
